- hosts: devops_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Git
      apt:
        name: git
        state: present
